name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - run: cargo build --workspace --all-features

  clippy:
    name: Clippy
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@v2
      with:
        tool: just
    - uses: actions/setup-java@v5
      if: runner.os == 'Windows'
      with:
        distribution: temurin
        java-version: 21
    - run: rustup target add wasm32-unknown-unknown
    - run: just check

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check format
      run: cargo fmt -- --check
    - name: Check spelling
      uses: crate-ci/typos@v1.24.4

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/install@cargo-docs-rs
    - run: rustup override set nightly
    - name: Build Docs
      run: cargo docs-rs
      env:
        RUSTDOCFLAGS: -Dwarnings
